### PR TITLE
137 use iris in hqdm rdf entity factories

### PR DESCRIPTION
**Pull request by twalmsley**
Comment copied from the corresponding issue:

So, if I changed only the `Rdf*Services` classes then that's only half the job - the classes in the `hqdm` module would still need conversion to and from IRIs in the rest of the code, so I decided to change them as well to reduce clutter further. In summary:

1. The `hqdm-rdf` module has been subsumed into the `hqdm` module. (I could have gone the other direction, but this seemed to be the right way to go).
2. Any use of the `RDF*Services` is now replaced by the `*Services` in the `hqdm` module.
3. There is no need to convert `IRI` objects to and from `String` objects when using the classes, and no need to create temporary `IRI` objects any more.

I have tested the impact on client code and it _is_ a breaking change, but it makes the MagmaCore library easier to use. The two projects I tried it on both have quite a few changes to make but the resulting code is less cluttered and less clunky.

### CODE REVIEW

**Review by twalmsley — COMMENTED** [review]
Looks like I can't approve this since it's my PR - looks good though so feel free to merge when you're ready 👍

**Comment by GCHQDeveloper42** [comment]
The `hqdm-rdf-canonical` module should probably now be renamed to `hqdm-canonical`.

**Review by twalmsley — COMMENTED** [review]
👍  Approved

**Review by GCHQDeveloper42 — APPROVED** [review]

**Review by GCHQDeveloper56 — COMMENTED** [review]
Well worth doing this as it results in far cleaner code and, importantly, the interfacing to services.  Looks good to me!

**Pull request merged**
