### PR TITLE
Add a functional programming example

### PR DESCRIPTION
**Pull request by twalmsley**
This example is an attempt at writing code in a style that results in a more readable program flow. The `test` method clearly shows the steps in the use case, even if there looks to be a lot of code. The hope is that the fine-grained functions can be made reusable in other contexts so that composing new use cases from existing functions may become easier.

### CODE REVIEW

**Comment by twalmsley** [comment]
The real question for this PR is whether the code is any easier to read and understand, and is it better structured - if not then I don't mind if this PR is rejected.

**Comment by GCHQDeveloper42** [comment]
I would prefer this to be made an executable class like the other examples, rather than a unit test.

**Comment by twalmsley** [comment]
> I would prefer this to be made an executable class like the other examples, rather than a unit test.

I can move it to `src/main/java` and add `main()` but will it ever be executed? We can't be sure the examples are correct unless they're executed when code changes - we might find out months later. It could be added as a build step but would need updating for every new example.

**Comment by GCHQDeveloper42** [comment]
> I can move it to `src/main/java` and add `main()` but will it ever be executed? We can't be sure the examples are correct unless they're executed when code changes - we might find out months later. It could be added as a build step but would need updating for every new example.

I take your point. Could you define the program in an example class and then execute it in a `FunctionalProgrammingExampleTest` suite?

**Review by GCHQDeveloper42 — APPROVED** [review]

**Pull request merged**
